version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: parquet
    versions:
    - 4.0.0
  - dependency-name: odbc-api
    versions:
    - 0.14.0
    - 0.20.0
  - dependency-name: assert_cmd
    versions:
    - 1.0.3
